name: Inspect QTfiles from iTunes Installer
on:
  workflow_dispatch:
    inputs:
      win64_url:
        description: 64-bit iTunes Installer for Windows
        required: true
        default: https://secure-appldnld.apple.com/itunes12/
      win32_url:
        description: 32-bit iTunes Installer for Windows
        required: true
        default: https://secure-appldnld.apple.com/itunes12/
      itunes_version:
        description: Version of iTunes Installer for Windows
        required: true
        default: 00.00.00
        
jobs:
  download:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bit: [iTunes64Setup, iTunesSetup]
        
    steps:
      - name: Download iTunes Installer 64-bit
        if: matrix.bit == 'iTunes64Setup'
        run: aria2c -x 16 -o iTunes64Setup.exe "${{ github.event.inputs.win64_url }}"
        
      - name: Download iTunes Installer 32-bit
        if: matrix.bit == 'iTunesSetup'
        run: aria2c -x 16 -o iTunesSetup.exe "${{ github.event.inputs.win32_url }}"
        
      - name: Upload ${{ matrix.bit }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.bit }}
          path: ${{ matrix.bit }}.exe
          
  extract:
    needs: download
    runs-on: windows-latest
    strategy:
      matrix:
        bit: [QTfiles64, QTfiles]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false
          
      - name: Move makeportable
        run: Move-Item .\makeportable\makeportable2.cmd makeportable2.cmd
        
      - name: Download iTunes Installer 64-bit
        if: matrix.bit == 'QTfiles64'
        uses: actions/download-artifact@v4
        with:
          name: iTunes64Setup
          
      - name: Download iTunes Installer 32-bit
        if: matrix.bit == 'QTfiles'
        uses: actions/download-artifact@v4
        with:
          name: iTunesSetup
          
      - name: Use makeportable to extract ${{ matrix.bit }} ${{ github.event.inputs.itunes_version }}
        shell: cmd
        run: makeportable2.cmd
        
      - name: Inspect contents of ${{ matrix.bit }} ${{ github.event.inputs.itunes_version }}
        working-directory: ${{ matrix.bit }}
        run: Get-ChildItem